#!/usr/bin/env python3
"""Turn a Google Fonts css2 response into self-hosted @font-face rules.

Downloads are already in assets/fonts/ under gstatic's opaque filenames. This
renames them to something readable and rewrites the CSS to point at /fonts/.
Only latin and latin-ext are kept -- latin-ext carries the Hungarian
o-double-acute (U+0151) and u-double-acute (U+0171) that BRAND.md requires.

Re-run with: python3 scripts/build-fonts.py <downloaded-css>
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "assets" / "fonts"
OUT = ROOT / "assets" / "css" / "fonts.css"

KEEP = {"latin", "latin-ext"}
SLUG = {"Archivo": "archivo", "IBM Plex Mono": "ibm-plex-mono"}

BLOCK = re.compile(
    r"/\*\s*(?P<subset>[\w-]+)\s*\*/\s*(?P<body>@font-face\s*\{[^}]*\})",
    re.S,
)


def main() -> int:
    src_css = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "/tmp/gf-latin.css")
    css = src_css.read_text()

    rules = []
    for m in BLOCK.finditer(css):
        subset, body = m.group("subset"), m.group("body")
        if subset not in KEEP:
            continue

        family = re.search(r"font-family:\s*'([^']+)'", body).group(1)
        weight = re.search(r"font-weight:\s*([\d ]+);", body).group(1).strip()
        url = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)

        old = FONT_DIR / url.rsplit("/", 1)[1]
        if not old.exists():
            print(f"missing download: {old.name}", file=sys.stderr)
            return 1

        variable = " " in weight
        tag = "var" if variable else weight
        new_name = f"{SLUG[family]}-{tag}-{subset}.woff2"
        old.rename(FONT_DIR / new_name)

        rules.append(
            body.replace(url, f"/fonts/{new_name}").rstrip()
        )
        print(f"  {old.name} -> {new_name}")

    header = (
        "/* Self-hosted so the site makes no third-party request.\n"
        "   Generated by scripts/build-fonts.py -- do not hand-edit.\n"
        "   latin-ext carries the Hungarian ő and ű. */\n\n"
    )
    OUT.write_text(header + "\n\n".join(rules) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} with {len(rules)} @font-face rules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
